ALTER SERVER ROLE [sysadmin] ADD MEMBER [LAPTOP-U6K7CB3E\alexa];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

